apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "ojp-server.fullname" . }}
  labels:
    {{- include "ojp-server.labels" . | nindent 4 }}
data:
  OJP_SERVER_PORT: {{ .Values.server.port | quote }}
  OJP_PROMETHEUS_PORT: {{ .Values.server.prometheusPort | quote }}
  OJP_SERVER_THREADPOOLSIZE: {{ .Values.server.threadPoolSize | quote }}
  OJP_SERVER_MAXREQUESTSIZE: {{ .Values.server.maxRequestSize | quote }}
  OJP_SERVER_CONNECTIONIDLETIMEOUT: {{ .Values.server.connectionIdleTimeout | quote }}
  OJP_SERVER_CIRCUITBREAKERTIMEOUT: {{ .Values.server.circuitBreakerTimeout | quote }}
  OJP_SERVER_CIRCUITBREAKERTHRESHOLD: {{ .Values.server.circuitBreakerThreshold | quote }}
  OJP_SERVER_ALLOWEDIPS: {{ .Values.server.allowedIps | quote }}
  OJP_PROMETHEUS_ALLOWEDIPS: {{ .Values.server.prometheusAllowedIps | quote }}
  OJP_OPENTELEMETRY_ENABLED: {{ .Values.server.opentelemetry.enabled | quote }}
  OJP_OPENTELEMETRY_ENDPOINT: {{ .Values.server.opentelemetry.endpoint | quote }}
  OJP_SERVER_SLOWQUERYSEGREGATION_ENABLED: {{ .Values.server.slowQuerySegregation.enabled | quote }}
  OJP_SERVER_SLOWQUERYSEGREGATION_SLOWSLOTPERCENTAGE: {{ .Values.server.slowQuerySegregation.slowSlotPercentage | quote }}
  OJP_SERVER_SLOWQUERYSEGREGATION_IDLETIMEOUT: {{ .Values.server.slowQuerySegregation.idleTimeout | quote }}
  OJP_SERVER_SLOWQUERYSEGREGATION_SLOWSLOTTIMEOUT: {{ .Values.server.slowQuerySegregation.slowSlotTimeout | quote }}
  OJP_SERVER_SLOWQUERYSEGREGATION_FASTSLOTTIMEOUT: {{ .Values.server.slowQuerySegregation.fastSlotTimeout | quote }}
  OJP_SERVER_LOGLEVEL: {{ .Values.server.logLevel | quote }}